# Generated by Django 5.1.3 on 2025-01-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Chu_Nha_Tro', 'Chu Nha Tro'), ('Nguoi_Thue_Tro', 'Nguoi Thue Tro')], default='Nguoi_Thue_Tro', max_length=20),
        ),
    ]
